### ISSUE TITLE
hotplugging additional interfaces not quite right

### ISSUE THREAD

**Issue by javacruft** [lxc/nova-compute-lxd#46]
I think nclxd is updating the configuration appropriately

```
$ lxc config show c53a03d3-d8c6-44bf-8e14-142567079410
name: c53a03d3-d8c6-44bf-8e14-142567079410
profiles:
- nclxd-profile
config:
  limits.cpus: "1"
  limits.memory: "536870912"
  raw.lxc: |
    lxc.console.logfile=/var/lib/lxd/containers/c53a03d3-d8c6-44bf-8e14-142567079410/console.log
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
devices:
  qbrc18dbc66-a4:
    hwaddr: fa:16:3e:f0:40:e7
    nictype: bridged
    parent: qbrc18dbc66-a4
    type: nic
  qbrcea8db04-cc:
    hwaddr: fa:16:3e:10:56:56
    name: eth1
    nictype: bridged
    parent: qbrcea8db04-cc
    type: nic
ephemeral: false
```
but from within the container, the mac address is not correct (ae:e6:a6:d4:00:21 vs fa:16:3e:10:56:56):
```
$ ip link
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
81: eth0@if82: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1300 qdisc pfifo_fast state UP mode DEFAULT group default qlen 1000
    link/ether fa:16:3e:f0:40:e7 brd ff:ff:ff:ff:ff:ff
86: eth1@if87: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state LOWERLAYERDOWN mode DEFAULT group default qlen 1000
    link/ether ae:e6:a6:d4:00:21 brd ff:ff:ff:ff:ff:ff
```

**Comment by javacruft** [comment]
If I stop and start the container:
```
$ ip link
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
88: eth0@if89: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1300 qdisc pfifo_fast state UP mode DEFAULT group default qlen 1000
    link/ether fa:16:3e:f0:40:e7 brd ff:ff:ff:ff:ff:ff
90: eth1@if91: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1300 qdisc pfifo_fast state UP mode DEFAULT group default qlen 1000
    link/ether fa:16:3e:10:56:56 brd ff:ff:ff:ff:ff:ff
```

**Comment by hallyn** [comment]
Which version of lxd is this?  With the ppa stable version 0.18-0ubuntu2~ubuntu14.04.1~ppa1 I get:

serge@sergeh2:~$ lxc config show u1
name: u1
profiles:
- default
config:
  volatile.base_image: 99810b551eec1353da55eaa9207e162bed22a879edd5f31d25e3e41a1ea242e9
  volatile.eth0.hwaddr: 00:16:3e:18:55:7a
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":800000,"Nsid":0,"Maprange":1127680},{"Isuid":false,"Isgid":true,"Hostid":800000,"Nsid":0,"Maprange":1127680}]'
devices:
  eth1:
    hwaddr: fa:16:3e:10:56:56
    nictype: bridged
    parent: lxcbr0
    type: nic
ephemeral: false

serge@sergeh2:~$ lxc exec u1 -- ifconfig -a
eth0      Link encap:Ethernet  HWaddr 00:16:3e:18:55:7a
          inet addr:10.0.3.24  Bcast:10.0.3.255  Mask:255.255.255.0
          inet6 addr: fe80::216:3eff:fe18:557a/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:55 errors:0 dropped:0 overruns:0 frame:0
          TX packets:49 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:14087 (14.0 KB)  TX bytes:5327 (5.3 KB)
eth1      Link encap:Ethernet  HWaddr fa:16:3e:10:56:56
          BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:16 errors:0 dropped:0 overruns:0 frame:0
          TX packets:16 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:1296 (1.2 KB)  TX bytes:1296 (1.2 KB)

**Comment by javacruft** [comment]
This was with the version that's in wily - 0.18-0ubuntu2
