### ISSUE TITLE
instances snapshots are not executable

### ISSUE THREAD

**Issue by javacruft** [lxc/nova-compute-lxd#56]
Create a snapshot of a instance, and then launch a new instance based on that snapshot;  nova attempts to spin up the container, however it quickly reverts back to a shutdown state.

Looking at the content of the image, it may be in the wrong format:
```
metadata.yaml
rootfs
rootfs/bin
rootfs/bin/bash
rootfs/bin/bunzip2
rootfs/bin/busybox
rootfs/bin/bzcat
rootfs/bin/bzcmp
rootfs/bin/bzdiff
rootfs/bin/bzegrep
rootfs/bin/bzexe
rootfs/bin/bzfgrep
rootfs/bin/bzgrep
...
```

**Comment by zulcss** [comment]
This should be fixed now
