### ISSUE TITLE
No interfaces after host reboot

### ISSUE THREAD

**Issue by peter-slovak** [lxc/nova-compute-lxd#62]
After rebooting the host (compute node) with LXD instances present, the necessary interfaces are not created in openvswitch (qbrXXX, qvbXXX and qvoXXX for every instance). Because of that, any attempt to start guest machines fails.

##### How to replicate:
- start an instance on a compute node that uses nclxd driver
- reboot the compute node
- after reboot, try to start the instance

I believe that #61 fixes this bug by implementing plug_vifs() driver method (along with its counterpart unplug_vifs() . I have tested the fix on Ubuntu 14.04 and Openstack Kilo.

**Comment by zulcss** [comment]
This has been fixed in a recent merge.
